use std::sync::Arc;

use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};
use tokio::sync::{mpsc, RwLock};
use tokio_util::sync::CancellationToken;

use crate::{
    agent::{AgentAnswer, AgentEngine},
    app::{GatewayStatus, HealthState},
    attachments::AttachmentManager,
    auth::AuthManager,
    config::AppConfig,
    control_plane::{SessionAiConfigInput, SessionAiService},
    event::{AppEvent, EventBus},
    memory::{MemoryScope, MemoryStore},
    presentation::{Action, Block, View},
    providers::{AgentEvent, ProviderProfileStore, ProviderRegistry, ProviderState},
    runtime::{
        AndroidBroker, AndroidOperation, CapabilityStatus, ExecutionPurpose, ProcessExecutor,
        RuntimeState, SystemAndroidBroker, TermuxCommand, TermuxExecutor,
    },
    session::{ChatMode, SessionManager},
    skills::{FilesystemSkills, SkillStore},
    storage::Storage,
    telegram::{commands::TelegramCommandRegistry, paginator::Paginator, TelegramScope},
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Command {
    Start,
    Help { topic: Option<String> },
    Login,
    Model,
    ModelPicker { page: usize },
    SetModel { model: String },
    NewSession,
    Session { page: usize },
    SwitchSession { session: String },
    RequestRenameSession { session: String },
    RenameSession { session: String, name: String },
    DeleteSession { session: String },
    ConfirmDeleteSession { session: String },
    ToggleSideChat,
    Status,
    Context,
    Stop,
    Retry,
    Yolo { enabled: Option<bool> },
    Skills { page: usize },
    SkillDetail { skill: String },
    Tools,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "data", rename_all = "snake_case")]
pub enum CommandResult {
    InfoView(View),
    ManagerView(View),
    Confirmation(View),
    InputRequest { view: View, command_prefix: String },
    StartCustomLogin,
    Agent(AgentAnswer),
    NoContent,
}

/// Parse the public Telegram command surface. This is deliberately strict: a
/// removed management route must be unknown here even though the richer CLI /
/// IPC management surface still uses typed manager APIs.
pub fn parse(input: &str) -> Result<Option<Command>> {
    let (name, args) = parse_command_parts(input)?;
    let Some(name) = name else {
        return Ok(None);
    };
    let canonical = TelegramCommandRegistry::canonical(&name)
        .ok_or_else(|| anyhow!("unknown command /{name}"))?;
    match canonical {
        "help" => Ok(Some(Command::Help {
            topic: args.first().map(|value| (*value).to_owned()),
        })),
        "login" if args.is_empty() => Ok(Some(Command::Login)),
        "login" => Err(anyhow!(
            "/login configures the Custom endpoint directly and accepts no provider argument"
        )),
        "start" if args.is_empty() => Ok(Some(Command::Start)),
        "model" if args.is_empty() => Ok(Some(Command::Model)),
        "new" if args.is_empty() => Ok(Some(Command::NewSession)),
        "sessions" if args.is_empty() => Ok(Some(Command::Session { page: 1 })),
        "btw" if args.is_empty() => Ok(Some(Command::ToggleSideChat)),
        "status" if args.is_empty() => Ok(Some(Command::Status)),
        "context" if args.is_empty() => Ok(Some(Command::Context)),
        "retry" if args.is_empty() => Ok(Some(Command::Retry)),
        "yolo" if args.is_empty() => Ok(Some(Command::Yolo { enabled: None })),
        "stop" if args.is_empty() => Ok(Some(Command::Stop)),
        "skills" if args.is_empty() => Ok(Some(Command::Skills { page: 1 })),
        "tools" if args.is_empty() => Ok(Some(Command::Tools)),
        _ => Err(anyhow!(
            "command /{name} does not accept textual subcommands; use its inline controls"
        )),
    }
}

/// Parse only command shapes generated by our own validated scoped menus.
/// User-authored Telegram text always passes through `parse` above.
fn parse_internal_callback(input: &str) -> Result<Option<Command>> {
    let (name, args) = parse_command_parts(input)?;
    let Some(name) = name else {
        return Ok(None);
    };
    let canonical = TelegramCommandRegistry::canonical(&name)
        .ok_or_else(|| anyhow!("unknown command /{name}"))?;
    let page = |value: Option<&&str>| -> Result<usize> {
        value
            .map(|value| {
                value
                    .parse::<usize>()
                    .map_err(|_| anyhow!("page must be a positive integer"))
            })
            .transpose()
            .map(|value| value.unwrap_or(1).max(1))
    };
    match canonical {
        "start" if args.is_empty() => Ok(Some(Command::Start)),
        "help" if args.len() <= 1 => Ok(Some(Command::Help {
            topic: args.first().map(|value| (*value).to_owned()),
        })),
        "login" if args.is_empty() => Ok(Some(Command::Login)),
        "new" if args.is_empty() => Ok(Some(Command::NewSession)),
        "btw" if args.is_empty() => Ok(Some(Command::ToggleSideChat)),
        "sessions" if args.is_empty() => Ok(Some(Command::Session { page: 1 })),
        "sessions" if args.len() == 1 => Ok(Some(Command::Session {
            page: page(args.first())?,
        })),
        "sessions" if args.first() == Some(&"switch") && args.len() == 2 => {
            Ok(Some(Command::SwitchSession {
                session: args[1].to_owned(),
            }))
        }
        "sessions" if args.first() == Some(&"rename") && args.len() == 2 => {
            Ok(Some(Command::RequestRenameSession {
                session: args[1].to_owned(),
            }))
        }
        "sessions" if args.first() == Some(&"rename") && args.len() >= 3 => {
            Ok(Some(Command::RenameSession {
                session: args[1].to_owned(),
                name: args[2..].join(" "),
            }))
        }
        "sessions" if args.first() == Some(&"delete") && args.len() == 2 => {
            Ok(Some(Command::DeleteSession {
                session: args[1].to_owned(),
            }))
        }
        "sessions" if args.first() == Some(&"delete-confirm") && args.len() == 2 => {
            Ok(Some(Command::ConfirmDeleteSession {
                session: args[1].to_owned(),
            }))
        }
        "model" if args.is_empty() => Ok(Some(Command::Model)),
        "model" if args.first() == Some(&"change") && args.len() <= 2 => {
            Ok(Some(Command::ModelPicker {
                page: page(args.get(1))?,
            }))
        }
        "model" if !args.is_empty() => Ok(Some(Command::SetModel {
            model: args.join(" "),
        })),
        "status" if args.is_empty() => Ok(Some(Command::Status)),
        "context" if args.is_empty() => Ok(Some(Command::Context)),
        "stop" if args.is_empty() => Ok(Some(Command::Stop)),
        "retry" if args.is_empty() => Ok(Some(Command::Retry)),
        "yolo" if args.is_empty() => Ok(Some(Command::Yolo { enabled: None })),
        "skills" if args.is_empty() => Ok(Some(Command::Skills { page: 1 })),
        "skills" if args.first() == Some(&"learned") && args.len() <= 2 => {
            Ok(Some(Command::Skills {
                page: page(args.get(1))?,
            }))
        }
        "skills" if args.first() == Some(&"detail") && args.len() == 2 => {
            Ok(Some(Command::SkillDetail {
                skill: args[1].to_owned(),
            }))
        }
        "tools" if args.is_empty() => Ok(Some(Command::Tools)),
        _ => Err(anyhow!("invalid internal Telegram callback command")),
    }
}

fn parse_command_parts(input: &str) -> Result<(Option<String>, Vec<&str>)> {
    let text = input.trim();
    if text.is_empty() || !text.starts_with('/') {
        return Ok((None, Vec::new()));
    }
    let mut parts = text[1..].split_whitespace();
    let name = parts
        .next()
        .unwrap_or_default()
        .split('@')
        .next()
        .unwrap_or_default()
        .to_ascii_lowercase();
    if name.is_empty() {
        return Err(anyhow!("command name is required"));
    }
    Ok((Some(name), parts.collect()))
}

pub struct CommandCore {
    config: Arc<RwLock<AppConfig>>,
    storage: Arc<Storage>,
    sessions: Arc<SessionManager>,
    providers: Arc<ProviderRegistry>,
    auth: Arc<AuthManager>,
    health: Arc<HealthState>,
    events: Arc<EventBus>,
    agent: AgentEngine,
    runtime: Option<Arc<RuntimeState>>,
    attachments: Option<Arc<AttachmentManager>>,
}

impl CommandCore {
    pub fn new(
        config: Arc<RwLock<AppConfig>>,
        storage: Arc<Storage>,
        sessions: Arc<SessionManager>,
        providers: Arc<ProviderRegistry>,
        auth: Arc<AuthManager>,
        health: Arc<HealthState>,
        events: Arc<EventBus>,
    ) -> Self {
        Self::build(
            config, storage, sessions, providers, auth, health, events, None, None,
        )
    }

    #[allow(clippy::too_many_arguments)]
    pub fn with_runtime(
        config: Arc<RwLock<AppConfig>>,
        storage: Arc<Storage>,
        sessions: Arc<SessionManager>,
        providers: Arc<ProviderRegistry>,
        auth: Arc<AuthManager>,
        health: Arc<HealthState>,
        events: Arc<EventBus>,
        runtime: Arc<RuntimeState>,
        attachments: Arc<AttachmentManager>,
    ) -> Self {
        Self::build(
            config,
            storage,
            sessions,
            providers,
            auth,
            health,
            events,
            Some(runtime),
            Some(attachments),
        )
    }

    #[allow(clippy::too_many_arguments)]
    fn build(
        config: Arc<RwLock<AppConfig>>,
        storage: Arc<Storage>,
        sessions: Arc<SessionManager>,
        providers: Arc<ProviderRegistry>,
        auth: Arc<AuthManager>,
        health: Arc<HealthState>,
        events: Arc<EventBus>,
        runtime: Option<Arc<RuntimeState>>,
        attachments: Option<Arc<AttachmentManager>>,
    ) -> Self {
        let agent_config = config
            .try_read()
            .map(|guard| guard.agent.clone())
            .unwrap_or_default();
        let agent = if let Some(runtime) = runtime.clone() {
            AgentEngine::with_runtime(
                sessions.clone(),
                storage.clone(),
                providers.clone(),
                agent_config,
                runtime,
                attachments.clone(),
            )
        } else {
            AgentEngine::with_config(
                sessions.clone(),
                storage.clone(),
                providers.clone(),
                agent_config,
            )
        };
        Self {
            config,
            storage,
            sessions,
            providers,
            auth,
            health,
            events,
            agent,
            runtime,
            attachments,
        }
    }

    pub async fn execute_text(&self, principal: &str, input: &str) -> Result<CommandResult> {
        self.execute_text_with_progress(principal, input, None)
            .await
    }

    pub async fn execute_text_with_progress(
        &self,
        principal: &str,
        input: &str,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<CommandResult> {
        self.execute_text_with_context(principal, None, input, progress, false, None)
            .await
    }

    pub async fn execute_text_in_telegram_scope(
        &self,
        principal: &str,
        scope: TelegramScope,
        input: &str,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<CommandResult> {
        self.execute_text_with_context(principal, Some(scope), input, progress, false, None)
            .await
    }

    /// Preserve the Telegram message work item's cancellation lineage through
    /// its agent run.  Non-Telegram callers retain the simpler independent
    /// entrypoints above.
    pub async fn execute_text_in_telegram_scope_with_cancellation(
        &self,
        principal: &str,
        scope: TelegramScope,
        input: &str,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
        cancellation: CancellationToken,
    ) -> Result<CommandResult> {
        self.execute_text_with_context(
            principal,
            Some(scope),
            input,
            progress,
            false,
            Some(cancellation),
        )
        .await
    }

    /// Execute a command emitted by a validated Telegram inline menu. The
    /// adapter has already checked owner, scope, menu id and revision before
    /// this internal callback grammar is accepted.
    pub async fn execute_callback_in_telegram_scope(
        &self,
        principal: &str,
        scope: TelegramScope,
        input: &str,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<CommandResult> {
        self.execute_text_with_context(principal, Some(scope), input, progress, true, None)
            .await
    }

    async fn execute_text_with_context(
        &self,
        principal: &str,
        scope: Option<TelegramScope>,
        input: &str,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
        telegram_internal: bool,
        cancellation: Option<CancellationToken>,
    ) -> Result<CommandResult> {
        let parsed = if telegram_internal {
            parse_internal_callback(input)?
        } else {
            parse(input)?
        };
        match parsed {
            Some(cmd) => self.execute_in_scope(principal, scope, cmd).await,
            None => {
                if !self.config.read().await.gateway.enabled {
                    return Err(anyhow!("gateway is disabled"));
                }
                let answer = match scope {
                    Some(scope) => match cancellation {
                        Some(cancellation) => {
                            self.agent
                                .submit_with_progress_in_scope_with_cancellation(
                                    principal,
                                    scope,
                                    input,
                                    progress,
                                    cancellation,
                                )
                                .await?
                        }
                        None => {
                            self.agent
                                .submit_with_progress_in_scope(principal, scope, input, progress)
                                .await?
                        }
                    },
                    None => {
                        self.agent
                            .submit_with_progress(principal, input, progress)
                            .await?
                    }
                };
                Ok(CommandResult::Agent(answer))
            }
        }
    }

    pub async fn chat_in_session(
        &self,
        principal: &str,
        session_id: &str,
        prompt: &str,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<CommandResult> {
        if !self.config.read().await.gateway.enabled {
            return Err(anyhow!("gateway is disabled"));
        }
        Ok(CommandResult::Agent(
            self.agent
                .submit_to_session_with_progress(principal, session_id, prompt, progress)
                .await?,
        ))
    }

    pub async fn retry_in_session(
        &self,
        principal: &str,
        session_id: &str,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<CommandResult> {
        if !self.config.read().await.gateway.enabled {
            return Err(anyhow!("gateway is disabled"));
        }
        Ok(CommandResult::Agent(
            self.agent
                .retry_to_session_with_progress(principal, session_id, progress)
                .await?,
        ))
    }

    pub async fn retry_with_progress(
        &self,
        principal: &str,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<CommandResult> {
        if !self.config.read().await.gateway.enabled {
            return Err(anyhow!("gateway is disabled"));
        }
        Ok(CommandResult::Agent(
            self.agent.retry_with_progress(principal, progress).await?,
        ))
    }

    pub async fn retry_with_progress_in_telegram_scope(
        &self,
        principal: &str,
        scope: TelegramScope,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<CommandResult> {
        if !self.config.read().await.gateway.enabled {
            return Err(anyhow!("gateway is disabled"));
        }
        Ok(CommandResult::Agent(
            self.agent
                .retry_with_progress_in_scope(principal, Some(scope), progress)
                .await?,
        ))
    }

    pub async fn retry_with_progress_in_telegram_scope_with_cancellation(
        &self,
        principal: &str,
        scope: TelegramScope,
        progress: Option<mpsc::UnboundedSender<AgentEvent>>,
        cancellation: CancellationToken,
    ) -> Result<CommandResult> {
        if !self.config.read().await.gateway.enabled {
            return Err(anyhow!("gateway is disabled"));
        }
        Ok(CommandResult::Agent(
            self.agent
                .retry_with_progress_in_scope_with_cancellation(
                    principal,
                    scope,
                    progress,
                    cancellation,
                )
                .await?,
        ))
    }

    pub async fn execute(&self, principal: &str, command: Command) -> Result<CommandResult> {
        self.execute_in_scope(principal, None, command).await
    }

    /// Management cancellation remains session-bound. Telegram runs are
    /// addressed through their originating topic scope; local runs use the
    /// installation-local session namespace.
    pub fn cancel_session_run(&self, principal: &str, session_id: &str) -> Result<bool> {
        let session = self
            .storage
            .session(principal, session_id)?
            .ok_or_else(|| anyhow!("session not found for owner"))?;
        if session.archived {
            return Ok(false);
        }
        let agent_cancelled = self.agent.cancel_session(principal, session_id);
        let attachment_cancelled = self
            .attachments
            .as_ref()
            .is_some_and(|attachments| attachments.cancel_ingest(principal, session_id));
        if agent_cancelled || attachment_cancelled {
            return Ok(true);
        }
        let scope = self
            .storage
            .telegram_scope_for_session(principal, session_id)?
            .map(|(chat_id, message_thread_id)| TelegramScope::new(chat_id, message_thread_id));
        Ok(self.agent.cancel_in_scope(principal, scope))
    }

    pub async fn management_doctor(&self, principal: &str) -> View {
        self.doctor_view(principal, None).await
    }

    /// Shared memory mutation used by Telegram command handling and by the
    /// typed admin API consumed by CLI/WebUI. Presentation layers must not
    /// implement memory semantics independently.
    pub fn management_memory_set(
        &self,
        principal: &str,
        scope: MemoryScope,
        category: &str,
        key: &str,
        value: &str,
        source: &str,
    ) -> Result<()> {
        let value = value.trim();
        if value.is_empty() {
            return Err(anyhow!("memory value is required"));
        }
        self.memory_store()
            .upsert(principal, scope, category, key, value, 1.0, source, None)?;
        Ok(())
    }

    pub fn management_memory_forget(
        &self,
        principal: &str,
        scope: MemoryScope,
        category: &str,
        key: &str,
    ) -> Result<bool> {
        self.memory_store()
            .delete(principal, scope, category, key, None)
    }

    pub fn management_skill_set_enabled(
        &self,
        principal: &str,
        skill: &str,
        enabled: bool,
    ) -> Result<()> {
        SkillStore::new(self.storage.clone()).set_enabled(principal, skill, enabled)?;
        self.storage.audit(
            principal,
            if enabled {
                "skill_enabled"
            } else {
                "skill_disabled"
            },
            &format!("skill_id={skill}"),
        )
    }

    pub fn management_skill_delete(&self, principal: &str, skill: &str) -> Result<()> {
        let store = SkillStore::new(self.storage.clone());
        let record = store
            .view(principal, skill)?
            .ok_or_else(|| anyhow!("skill not found"))?;
        if record.source_kind != "learned" {
            return Err(anyhow!("only learned owner-created skills can be deleted"));
        }
        if let Some(runtime) = &self.runtime {
            runtime.workspace().delete_learned_skill(&record.name)?;
        }
        store.delete_learned(principal, &record.id)?;
        self.storage.audit(
            principal,
            "learned_skill_deleted",
            &format!("skill_id={};name={}", record.id, record.name),
        )
    }

    pub fn management_approval_decide(
        &self,
        principal: &str,
        request: &str,
        approve: bool,
    ) -> Result<bool> {
        self.storage.decide_approval(principal, request, approve)
    }

    /// Shared exact-session AI mutation used by Telegram command handling and
    /// the typed admin API consumed by CLI/WebUI. No active frontend pointer
    /// is read or changed by this operation.
    pub fn management_set_session_ai(
        &self,
        principal: &str,
        session_id: &str,
        provider: &str,
        account_or_profile_id: Option<String>,
        model: &str,
    ) -> Result<crate::storage::SessionRecord> {
        SessionAiService::new(self.storage.clone(), self.providers.clone()).apply(
            principal,
            SessionAiConfigInput {
                session_id: session_id.to_owned(),
                provider: provider.to_owned(),
                account_or_profile_id,
                model: model.to_owned(),
            },
        )
    }

    pub async fn execute_in_scope(
        &self,
        principal: &str,
        scope: Option<TelegramScope>,
        command: Command,
    ) -> Result<CommandResult> {
        use Command::*;
        match command {
            Start => Ok(CommandResult::InfoView(View {
                title: None,
                blocks: vec![Block::Paragraph {
                    text: "Hello! I'm Xiao. How can I help you today?".into(),
                }],
                actions: Vec::new(),
                side_mode: false,
            })),
            NewSession => {
                let s = match scope {
                    Some(scope) => self.sessions.create_and_switch_telegram(principal, scope)?,
                    None => self.sessions.create_and_switch(principal)?,
                };
                self.events.publish(AppEvent::SessionChanged {
                    principal: principal.into(),
                    session_id: s.id.clone(),
                });
                let mut view =
                    View::info("NEW SESSION", format!("Created and activated {}", s.name));
                view.actions = vec![vec![
                    Action::command("Session Manager", "/sessions"),
                    Action::close(),
                ]];
                Ok(CommandResult::Confirmation(view))
            }
            ToggleSideChat => {
                let c = match scope {
                    Some(scope) => self.sessions.toggle_telegram_side(principal, scope)?,
                    None => self.sessions.toggle_side(principal)?,
                };
                let text = if c.mode == ChatMode::Side {
                    format!("SIDE CHAT SESSION\nParent: {}", c.main.name)
                } else {
                    format!("Returned to MAIN SESSION\n{}", c.main.name)
                };
                Ok(CommandResult::Confirmation(View::info(
                    "SESSION MODE",
                    text,
                )))
            }
            Session { page } => Ok(CommandResult::ManagerView(
                self.session_view(principal, scope, page)?,
            )),
            SwitchSession { session } => {
                let s = match scope {
                    Some(scope) => self
                        .sessions
                        .switch_telegram_main(principal, scope, &session)?,
                    None => self.sessions.switch_main(principal, &session)?,
                };
                self.events.publish(AppEvent::SessionChanged {
                    principal: principal.into(),
                    session_id: s.id.clone(),
                });
                Ok(CommandResult::ManagerView(self.session_view_with_notice(
                    principal,
                    scope,
                    1,
                    format!("Active: {}", s.name),
                )?))
            }
            RequestRenameSession { session } => {
                self.validate_session_scope(principal, scope, &session)?;
                let target = self
                    .storage
                    .session(principal, &session)?
                    .ok_or_else(|| anyhow!("session not found"))?;
                if target.is_side || target.archived {
                    return Err(anyhow!("session is not renameable"));
                }
                let view = View {
                    title: Some("RENAME SESSION".into()),
                    blocks: vec![Block::Paragraph {
                        text: format!(
                            "Current name: {}\nSend the new name as your next message.",
                            target.name
                        ),
                    }],
                    actions: vec![vec![Action::back(), Action::close()]],
                    side_mode: false,
                };
                Ok(CommandResult::InputRequest {
                    view,
                    command_prefix: format!("/sessions rename {}", target.id),
                })
            }
            RenameSession { session, name } => {
                self.validate_session_scope(principal, scope, &session)?;
                let name = name.trim();
                if name.is_empty() {
                    return Err(anyhow!("new session name required"));
                }
                if name.chars().count() > 120 {
                    return Err(anyhow!("session name must be 120 characters or fewer"));
                }
                self.storage.rename_session(principal, &session, name)?;
                Ok(CommandResult::ManagerView(self.session_view_with_notice(
                    principal,
                    scope,
                    1,
                    "Session renamed.".into(),
                )?))
            }
            DeleteSession { session } => {
                self.validate_session_scope(principal, scope, &session)?;
                let target = self
                    .storage
                    .session(principal, &session)?
                    .ok_or_else(|| anyhow!("session not found"))?;
                if target.is_side || target.archived {
                    return Err(anyhow!("session is not deletable from the main manager"));
                }
                let mut view = View::info(
                    "DELETE SESSION",
                    format!(
                        "Permanently delete {} and its conversation history? Owner-global USER/MEMORY/SKILLS and Custom profiles are preserved.",
                        target.name
                    ),
                );
                view.actions = vec![
                    vec![Action::command(
                        "Delete permanently",
                        format!("/sessions delete-confirm {}", target.id),
                    )],
                    vec![Action::back(), Action::close()],
                ];
                Ok(CommandResult::Confirmation(view))
            }
            ConfirmDeleteSession { session } => {
                self.validate_session_scope(principal, scope, &session)?;
                let (active, deleted) = match scope {
                    Some(scope) => self
                        .sessions
                        .delete_and_recover_telegram(principal, scope, &session)?,
                    None => self.sessions.delete_and_recover(principal, &session)?,
                };
                let cleanup_warning = self
                    .attachments
                    .as_ref()
                    .and_then(|attachments| {
                        attachments
                            .cleanup_deleted_session_paths(&deleted.attachment_paths)
                            .err()
                    })
                    .map(|error| crate::security::redact::redact_text(&error.to_string()));
                self.storage.audit(
                    principal,
                    "session_deleted",
                    &format!(
                        "session_id={session};replacement_session_id={};attachment_cleanup_warning={}",
                        active.id,
                        cleanup_warning.as_deref().unwrap_or("none")
                    ),
                )?;
                self.events.publish(AppEvent::SessionChanged {
                    principal: principal.into(),
                    session_id: active.id.clone(),
                });
                let notice = match cleanup_warning {
                    Some(warning) => format!(
                        "Deleted session. Active: {}. Attachment cleanup deferred: {}",
                        active.name, warning
                    ),
                    None => format!("Deleted session. Active: {}", active.name),
                };
                Ok(CommandResult::ManagerView(
                    self.session_view_with_notice(principal, scope, 1, notice)?,
                ))
            }
            Model => Ok(CommandResult::ManagerView(
                self.model_view(principal, scope)?,
            )),
            ModelPicker { page } => Ok(CommandResult::ManagerView(
                self.model_picker_view(principal, scope, page)?,
            )),
            SetModel { model } => {
                let context = self.session_context(principal, scope)?;
                if context.active.provider == "custom" {
                    let profile_id = context.active.account_id.as_deref().ok_or_else(|| {
                        anyhow!("select a Custom profile before selecting a Custom model")
                    })?;
                    let _model_record = ProviderProfileStore::new(self.storage.clone())
                        .model(profile_id, &model)?
                        .ok_or_else(|| anyhow!("model is not in the provider catalog"))?;
                }
                self.set_model(principal, scope, &model)?;
                self.events.publish(AppEvent::ModelChanged {
                    principal: principal.into(),
                    model,
                });
                Ok(CommandResult::ManagerView(
                    self.model_view(principal, scope)?,
                ))
            }
            Login => Ok(CommandResult::StartCustomLogin),
            Status => Ok(CommandResult::InfoView(
                self.status_view(principal, scope).await?,
            )),
            Context => Ok(CommandResult::InfoView(
                self.context_view(principal, scope).await?,
            )),
            Stop => Ok(CommandResult::Confirmation(View::info(
                "STOP",
                if self.cancel_active_scope(principal, scope)? {
                    "Cancellation requested"
                } else {
                    "No active generation"
                },
            ))),
            Retry => {
                let answer = self
                    .agent
                    .retry_with_progress_in_scope(principal, scope, None)
                    .await?;
                Ok(CommandResult::Agent(answer))
            }
            Yolo { enabled } => {
                let context = self.session_context(principal, scope)?;
                let enabled = enabled.unwrap_or(!context.active.yolo_mode);
                self.storage
                    .set_session_yolo(principal, &context.active.id, enabled)?;
                self.storage.audit(
                    principal,
                    if enabled {
                        "yolo_enabled"
                    } else {
                        "yolo_disabled"
                    },
                    &format!("session_id={};mode=immediate_toggle", context.active.id),
                )?;
                Ok(CommandResult::ManagerView(View::info(
                    "YOLO",
                    format!(
                        "YOLO {} for {}",
                        if enabled { "ON" } else { "OFF" },
                        context.active.name
                    ),
                )))
            }
            Skills { page } => Ok(CommandResult::ManagerView(
                self.telegram_skills_view(principal, page)?,
            )),
            SkillDetail { skill } => Ok(CommandResult::ManagerView(
                self.telegram_skill_detail_view(principal, &skill)?,
            )),
            Tools => Ok(CommandResult::ManagerView(self.tools_view())),
            Help { .. } => Ok(CommandResult::InfoView(help_view())),
        }
    }

    fn cancel_active_scope(&self, principal: &str, scope: Option<TelegramScope>) -> Result<bool> {
        let agent_cancelled = self.agent.cancel_in_scope(principal, scope);
        let attachment_cancelled = self
            .attachments
            .as_ref()
            .and_then(|attachments| {
                self.session_context(principal, scope)
                    .ok()
                    .map(|context| attachments.cancel_ingest(principal, &context.active.id))
            })
            .unwrap_or(false);
        Ok(agent_cancelled || attachment_cancelled)
    }

    fn session_view(
        &self,
        principal: &str,
        scope: Option<TelegramScope>,
        page: usize,
    ) -> Result<View> {
        self.session_view_with_notice(principal, scope, page, String::new())
    }

    fn session_view_with_notice(
        &self,
        principal: &str,
        scope: Option<TelegramScope>,
        page: usize,
        notice: String,
    ) -> Result<View> {
        let (rows, pages, page) = match scope {
            Some(scope) => self
                .sessions
                .list_telegram_page(principal, scope, page, 5)?,
            None => self.sessions.list_page(principal, page, 5)?,
        };
        let active = self.session_context(principal, scope)?.main.id;
        let mut blocks = vec![];
        if !notice.is_empty() {
            blocks.push(Block::Paragraph { text: notice });
        }
        blocks.push(Block::Table {
            headers: vec![
                "No".into(),
                "Active".into(),
                "Session".into(),
                "Messages".into(),
            ],
            rows: rows
                .iter()
                .enumerate()
                .map(|(i, s)| {
                    vec![
                        (i + 1).to_string(),
                        if s.id == active {
                            "●".into()
                        } else {
                            "".into()
                        },
                        s.name.clone(),
                        s.message_count.to_string(),
                    ]
                })
                .collect(),
        });
        let mut actions = vec![];
        if !rows.is_empty() {
            actions.push(
                rows.iter()
                    .enumerate()
                    .map(|(i, s)| {
                        Action::command((i + 1).to_string(), format!("/sessions switch {}", s.id))
                    })
                    .collect(),
            );
        }
        actions.push(vec![
            Action::command("‹", format!("/sessions {}", page.saturating_sub(1).max(1))),
            Action::noop(format!("{page}/{pages}")),
            Action::command("›", format!("/sessions {}", (page + 1).min(pages))),
        ]);
        actions.push(vec![
            Action::command("New", "/new"),
            Action::command("Rename", format!("/sessions rename {active}")),
            Action::command("Delete", format!("/sessions delete {active}")),
        ]);
        actions.push(vec![Action::close()]);
        Ok(View {
            title: Some("SESSIONS".into()),
            blocks,
            actions,
            side_mode: false,
        })
    }

    fn model_view(&self, principal: &str, scope: Option<TelegramScope>) -> Result<View> {
        self.model_picker_view(principal, scope, 1)
    }

    fn model_picker_view(
        &self,
        principal: &str,
        scope: Option<TelegramScope>,
        page: usize,
    ) -> Result<View> {
        let c = self.session_context(principal, scope)?;
        if c.active.provider != "custom" {
            return Ok(View::info(
                "CUSTOM MODEL REQUIRED",
                "This legacy conversation remains readable, but its previous provider is no longer active. Configure a Custom endpoint with /login, then select a model here before generating.",
            ));
        }
        let Some(profile_id) = c.active.account_id.as_deref() else {
            return Ok(View::info(
                "CUSTOM MODEL REQUIRED",
                "No Custom profile is selected for this session. Configure one with /login.",
            ));
        };
        let profiles = ProviderProfileStore::new(self.storage.clone());
        let profile = profiles
            .get(principal, profile_id)?
            .ok_or_else(|| anyhow!("selected Custom profile is unavailable"))?;
        let models = profiles
            .models(profile_id)?
            .into_iter()
            .map(|model| model.model_id)
            .collect::<Vec<_>>();
        let pagination = Paginator::new(models.len(), page, 5);
        let visible = models[pagination.range()].to_vec();
        let current_model = profiles.model(profile_id, &c.active.model)?;
        let capability =
            self.providers
                .capabilities_for("custom", &c.active.model, Some(profile_id))?;
        let mut blocks = vec![Block::Table {
            headers: vec!["Field".into(), "Value".into()],
            rows: vec![
                vec!["CUSTOM ALIAS".into(), profile.alias.clone()],
                vec!["ENDPOINT".into(), profile.endpoint.clone()],
                vec!["ACTIVE MODEL".into(), c.active.model.clone()],
                vec!["TOOLS".into(), capability.tool_protocol.as_str().into()],
                vec![
                    "VISION".into(),
                    current_model
                        .as_ref()
                        .map(|model| model.vision_state.clone())
                        .unwrap_or_else(|| "unknown".into()),
                ],
                vec![
                    "FILE INPUT".into(),
                    current_model
                        .as_ref()
                        .map(|model| model.file_input_state.clone())
                        .unwrap_or_else(|| "unknown".into()),
                ],
            ],
        }];
        let rows = visible
            .iter()
            .enumerate()
            .map(|(index, m)| {
                vec![
                    (index + 1).to_string(),
                    m.clone(),
                    if *m == c.active.model {
                        "●".into()
                    } else {
                        "".into()
                    },
                ]
            })
            .collect();
        blocks.push(Block::Table {
            headers: vec!["No".into(), "Discovered model".into(), "Current".into()],
            rows,
        });
        let mut actions = vec![visible
            .into_iter()
            .enumerate()
            .map(|(index, model)| {
                Action::command((index + 1).to_string(), format!("/model {model}"))
            })
            .collect::<Vec<_>>()];
        actions.push(vec![
            Action::command("‹", format!("/model change {}", pagination.previous())),
            Action::noop(format!("Page {}/{}", pagination.page(), pagination.pages())),
            Action::command("›", format!("/model change {}", pagination.next())),
        ]);
        actions.push(vec![Action::close()]);
        Ok(View {
            title: Some("CUSTOM MODEL".into()),
            blocks,
            actions,
            side_mode: false,
        })
    }

    fn set_model(&self, principal: &str, scope: Option<TelegramScope>, model: &str) -> Result<()> {
        let c = self.session_context(principal, scope)?;
        if !self
            .providers
            .models_for(&c.active.provider, c.active.account_id.as_deref())?
            .iter()
            .any(|m| m == model)
        {
            return Err(anyhow!("model is not in the provider catalog"));
        }
        if let Some(binding) = c.active.account_id.clone() {
            self.management_set_session_ai(
                principal,
                &c.active.id,
                &c.active.provider,
                Some(binding),
                model,
            )?;
            Ok(())
        } else {
            // Compatibility for an inert pre-profile Custom default session.
            self.storage.set_session_provider(
                principal,
                &c.active.id,
                &c.active.provider,
                None,
                model,
            )
        }
    }

    fn session_context(
        &self,
        principal: &str,
        scope: Option<TelegramScope>,
    ) -> Result<crate::session::SessionContext> {
        match scope {
            Some(scope) => self.sessions.context_for_telegram(principal, scope),
            None => self.sessions.context_for(principal),
        }
    }

    fn validate_session_scope(
        &self,
        principal: &str,
        scope: Option<TelegramScope>,
        session_id: &str,
    ) -> Result<()> {
        if let Some(scope) = scope {
            let bound = self
                .storage
                .telegram_scope_for_session(principal, session_id)?;
            if bound != Some((scope.chat_id, scope.message_thread_id)) {
                return Err(anyhow!("session is not in this Telegram topic"));
            }
        }
        Ok(())
    }

    async fn status_view(&self, principal: &str, scope: Option<TelegramScope>) -> Result<View> {
        let cfg = self.config.read().await.clone();
        let health = self
            .health
            .snapshot(&cfg, self.storage.health(), self.providers.states())
            .await;
        let c = self.session_context(principal, scope)?;
        let selected_state = health
            .provider_states
            .get(&c.active.provider)
            .cloned()
            .unwrap_or(ProviderState::Error);
        let provider_state = format!("{selected_state:?}").to_uppercase();
        // `/status` is principal/session aware. A globally healthy daemon is still a
        // degraded gateway for this principal when the selected provider cannot serve
        // requests (expired credential, missing login/configuration, etc.).
        let gateway = if matches!(&health.gateway, GatewayStatus::Running)
            && selected_state != ProviderState::Ready
        {
            GatewayStatus::Degraded
        } else {
            health.gateway.clone()
        };
        let environment = self.runtime.as_ref().map(|runtime| runtime.environment());
        let skills = SkillStore::new(self.storage.clone())
            .list(principal, 500)?
            .len();
        let latest_run = self
            .storage
            .agent_runs(principal, 20)?
            .into_iter()
            .find(|run| run.session_id == c.active.id && run.status == "running");
        Ok(View {
            title: Some("STATUS".into()),
            blocks: vec![Block::Table {
                headers: vec!["Field".into(), "Value".into()],
                rows: vec![
                    vec![
                        "Agent".into(),
                        if self.agent.is_active_in_scope(principal, scope) {
                            "RUNNING".into()
                        } else if matches!(gateway, GatewayStatus::Running) {
                            "READY".into()
                        } else {
                            format!("{:?}", gateway).to_uppercase()
                        },
                    ],
                    vec![
                        "Daemon".into(),
                        if health.daemon_running {
                            "RUNNING".into()
                        } else {
                            "STOPPED".into()
                        },
                    ],
                    vec![
                        "Telegram".into(),
                        if health.telegram_polling {
                            "POLLING".into()
                        } else {
                            "IDLE".into()
                        },
                    ],
                    vec![
                        "DB".into(),
                        if health.db_healthy {
                            "HEALTHY".into()
                        } else {
                            "ERROR".into()
                        },
                    ],
                    vec![
                        "Provider".into(),
                        format!("{} · {}", c.active.provider, provider_state),
                    ],
                    vec!["Model".into(), c.active.model],
                    vec!["Session".into(), c.main.name],
                    vec![
                        "Topic".into(),
                        scope
                            .and_then(|scope| scope.message_thread_id)
                            .map(|thread| thread.to_string())
                            .unwrap_or_else(|| "default".into()),
                    ],
                    vec![
                        "YOLO".into(),
                        if c.active.yolo_mode {
                            "ON".into()
                        } else {
                            "OFF".into()
                        },
                    ],
                    vec![
                        "Termux".into(),
                        if environment.as_ref().is_some_and(|env| env.termux.is_some()) {
                            "READY".into()
                        } else {
                            "UNAVAILABLE".into()
                        },
                    ],
                    vec![
                        "Root broker".into(),
                        if environment
                            .as_ref()
                            .is_some_and(|env| env.effective_uid == 0)
                        {
                            "READY".into()
                        } else {
                            "UNAVAILABLE".into()
                        },
                    ],
                    vec!["Memory".into(), "READY".into()],
                    vec!["Skills".into(), skills.to_string()],
                    vec![
                        "Running task".into(),
                        latest_run
                            .and_then(|run| run.goal)
                            .unwrap_or_else(|| "—".into()),
                    ],
                ],
            }],
            actions: vec![],
            side_mode: c.mode == ChatMode::Side,
        })
    }

    async fn context_view(&self, principal: &str, scope: Option<TelegramScope>) -> Result<View> {
        let c = self.session_context(principal, scope)?;
        let main = self.storage.messages(principal, &c.main.id)?;
        let side = if c.mode == ChatMode::Side {
            self.storage.messages(principal, &c.active.id)?
        } else {
            Vec::new()
        };
        let effective_count = main.len() + side.len();
        let chars = main
            .iter()
            .chain(side.iter())
            .map(|message| message.content.chars().count())
            .sum::<usize>();
        let memories = MemoryStore::new(self.storage.clone())
            .list(principal, None, 200)?
            .len();
        let skills = SkillStore::new(self.storage.clone())
            .list(principal, 500)?
            .len();
        let summarized = self
            .storage
            .session_summary(principal, &c.main.id)?
            .is_some();
        let context_budget = self.config.read().await.agent.context_max_chars;
        Ok(View {
            title: Some("CONTEXT".into()),
            blocks: vec![Block::Table {
                headers: vec!["Field".into(), "Value".into()],
                rows: vec![
                    vec!["Main messages".into(), c.main.message_count.to_string()],
                    vec!["Effective messages".into(), effective_count.to_string()],
                    vec!["Stored characters".into(), chars.to_string()],
                    vec!["Context budget".into(), format!("{context_budget} chars")],
                    vec![
                        "Summary".into(),
                        if summarized {
                            "AVAILABLE".into()
                        } else {
                            "NOT NEEDED".into()
                        },
                    ],
                    vec!["Active memory entries".into(), memories.to_string()],
                    vec!["Skills available".into(), skills.to_string()],
                    vec![
                        "Provider / model".into(),
                        format!("{} / {}", c.active.provider, c.active.model),
                    ],
                    vec!["Mode".into(), c.mode.as_str().to_uppercase()],
                    vec![
                        "Side isolation".into(),
                        if c.mode == ChatMode::Side {
                            "READ MAIN + WRITE SIDE".into()
                        } else {
                            "MAIN".into()
                        },
                    ],
                ],
            }],
            actions: vec![],
            side_mode: c.mode == ChatMode::Side,
        })
    }

    async fn doctor_view(&self, principal: &str, scope: Option<TelegramScope>) -> View {
        let cfg = self.config.read().await.clone();
        let environment = self.runtime.as_ref().map(|runtime| runtime.environment());
        let mut checks = Vec::new();
        let mut check = |state: &str, name: &str, evidence: String| {
            checks.push(format!("{state} · {name} · {evidence}"));
        };

        match self.storage.diagnostic_transaction() {
            Ok(()) => check(
                "PASS",
                "DB transaction",
                "begin/read/rollback succeeded".into(),
            ),
            Err(error) => check("FAIL", "DB transaction", safe_diagnostic(&error)),
        }
        match self.storage.schema_version() {
            Ok(27) => check("PASS", "Migrations/schema", "schema version 27".into()),
            Ok(version) => check(
                "FAIL",
                "Migrations/schema",
                format!("expected 26, found {version}"),
            ),
            Err(error) => check("FAIL", "Migrations/schema", safe_diagnostic(&error)),
        }
        match self
            .runtime
            .as_ref()
            .map(|runtime| runtime.workspace().load())
        {
            Some(Ok(workspace)) if !workspace.soul.trim().is_empty() => check(
                "PASS",
                "Identity workspace",
                "SOUL/USER/MEMORY/AGENTS readable".into(),
            ),
            Some(Ok(_)) => check("FAIL", "Identity workspace", "SOUL.md is empty".into()),
            Some(Err(error)) => check("FAIL", "Identity workspace", safe_diagnostic(&error)),
            None => check(
                "SKIPPED",
                "Identity workspace",
                "runtime not attached".into(),
            ),
        }

        let memory = self.memory_store();
        match memory.list(principal, None, 1).and_then(|_| {
            memory
                .search(principal, "doctor probe nonce", 1)
                .map(|_| ())
        }) {
            Ok(()) => check(
                "PASS",
                "Memory reconcile/search",
                "active index and FTS query succeeded; canonical files readable in identity probe"
                    .into(),
            ),
            Err(error) => check("FAIL", "Memory reconcile/search", safe_diagnostic(&error)),
        }

        let skills = SkillStore::new(self.storage.clone());
        let skill_result = if let Some(runtime) = &self.runtime {
            FilesystemSkills::new(runtime.workspace(), Arc::new(skills.clone()))
                .discover()
                .and_then(|_| {
                    skills
                        .search(principal, "doctor probe nonce", 1)
                        .map(|_| ())
                })
        } else {
            skills
                .search(principal, "doctor probe nonce", 1)
                .map(|_| ())
        };
        match skill_result {
            Ok(()) => check(
                "PASS",
                "Skills scan/search",
                "filesystem/index/FTS readable".into(),
            ),
            Err(error) => check("FAIL", "Skills scan/search", safe_diagnostic(&error)),
        }

        match self.storage.session_fts_health() {
            Ok(rows) => check(
                "PASS",
                "Session FTS",
                format!("index readable; {rows} rows"),
            ),
            Err(error) => check("FAIL", "Session FTS", safe_diagnostic(&error)),
        }
        match &self.attachments {
            Some(attachments) => {
                match attachments.health() {
                    Ok(evidence) => check("PASS", "Attachment store/FTS", evidence),
                    Err(error) => check("FAIL", "Attachment store/FTS", safe_diagnostic(&error)),
                }
                match attachments.usage(principal) {
                    Ok(usage) => check(
                        "PASS",
                        "Attachment storage usage",
                        format!(
                            "owner={}/{} bytes; global={}/{} bytes",
                            usage.owner_bytes,
                            usage.owner_quota_bytes,
                            usage.global_bytes,
                            usage.global_quota_bytes
                        ),
                    ),
                    Err(error) => {
                        check("WARN", "Attachment storage usage", safe_diagnostic(&error))
                    }
                }
            }
            None => check(
                "SKIPPED",
                "Attachment store/FTS",
                "manager not attached".into(),
            ),
        }

        if cfg.telegram.enabled {
            let token = self
                .storage
                .telegram_control_state()
                .ok()
                .flatten()
                .and_then(|control| control.bot_token_ref)
                .and_then(|reference| {
                    crate::security::secrets::SecretStore::new(cfg.paths.secrets_dir.clone())
                        .get(&reference)
                        .ok()
                        .flatten()
                });
            match token {
                Some(token) => match crate::telegram::client::TelegramClient::new(token) {
                    Ok(client) => match tokio::time::timeout(
                        std::time::Duration::from_secs(10),
                        client.get_me(),
                    )
                    .await
                    {
                        Ok(Ok(bot)) => {
                            check("PASS", "Telegram API", format!("getMe bot_id={}", bot.id))
                        }
                        Ok(Err(error)) => check("WARN", "Telegram API", safe_diagnostic(&error)),
                        Err(_) => check("WARN", "Telegram API", "getMe timed out".into()),
                    },
                    Err(error) => check("FAIL", "Telegram API", safe_diagnostic(&error)),
                },
                None => check("FAIL", "Telegram API", "bot token is not configured".into()),
            }
        } else {
            check("SKIPPED", "Telegram API", "Telegram is disabled".into());
        }

        if let (Some(runtime), Some(termux)) = (
            &self.runtime,
            environment.as_ref().and_then(|env| env.termux.clone()),
        ) {
            let executor = TermuxExecutor::new(termux.clone(), runtime.workspace().root());
            let command = TermuxCommand {
                program: "true".into(),
                args: Vec::new(),
                cwd: termux.home,
                environment: Default::default(),
                timeout_ms: 5_000,
                max_output_chars: 256,
                purpose: ExecutionPurpose::Verification,
            };
            match executor
                .execute(command, tokio_util::sync::CancellationToken::new())
                .await
            {
                Ok(outcome) if outcome.succeeded() => {
                    check("PASS", "Termux executor", outcome.observable_summary())
                }
                Ok(outcome) => check("WARN", "Termux executor", outcome.observable_summary()),
                Err(error) => check("WARN", "Termux executor", safe_diagnostic(&error)),
            }
        } else {
            check(
                "SKIPPED",
                "Termux executor",
                "Termux environment unavailable".into(),
            );
        }

        if let Some(runtime) = &self.runtime {
            let resolution = runtime.capabilities().resolve("xiao.tool_registry");
            check(
                if resolution.status == CapabilityStatus::Available {
                    "PASS"
                } else {
                    "WARN"
                },
                "CapabilityRegistry",
                format!("{}={}", resolution.canonical, resolution.status.as_str()),
            );
        } else {
            check(
                "SKIPPED",
                "CapabilityRegistry",
                "runtime not attached".into(),
            );
        }

        if environment
            .as_ref()
            .is_some_and(|env| env.effective_uid == 0)
            && std::path::Path::new("/system/bin/getprop").is_file()
        {
            match SystemAndroidBroker::default()
                .execute(
                    AndroidOperation::InspectXiaoService,
                    tokio_util::sync::CancellationToken::new(),
                )
                .await
            {
                Ok(outcome) if outcome.verified => {
                    check("PASS", "Android broker", outcome.evidence)
                }
                Ok(outcome) => check("WARN", "Android broker", outcome.evidence),
                Err(error) => check("WARN", "Android broker", safe_diagnostic(&error)),
            }
        } else {
            check(
                "SKIPPED",
                "Android broker",
                "safe getprop probe unavailable in this runtime".into(),
            );
        }

        match self.session_context(principal, scope) {
            Ok(context) => {
                let provider_state = self.providers.state(&context.active.provider);
                check(
                    if provider_state == ProviderState::Ready {
                        "PASS"
                    } else {
                        "WARN"
                    },
                    "Active provider/auth/model",
                    format!(
                        "LOCAL state · {} / {} / {:?}",
                        context.active.provider, context.active.model, provider_state
                    ),
                );
                if context.active.provider == "custom" {
                    let profiles = ProviderProfileStore::new(self.storage.clone());
                    match context
                        .active
                        .account_id
                        .as_deref()
                        .ok_or_else(|| anyhow!("active Custom session has no profile binding"))
                        .and_then(|profile_id| {
                            profiles
                                .get(principal, profile_id)?
                                .ok_or_else(|| anyhow!("active Custom profile is missing"))
                        }) {
                        Ok(profile) => {
                            let headers = profile.safe_headers().unwrap_or_default();
                            let api_key = profile
                                .credential_ref
                                .as_deref()
                                .and_then(|reference| {
                                    self.auth.credential(reference).ok().flatten()
                                })
                                .and_then(|credential| credential.api_key);
                            let live = tokio::time::timeout(
                                std::time::Duration::from_secs(12),
                                crate::ipc::fetch_custom_models(
                                    &profile.endpoint,
                                    &headers,
                                    api_key.as_deref(),
                                ),
                            )
                            .await;
                            match live {
                                Ok(Ok(models)) if models.iter().any(|model| model == &context.active.model) => check(
                                    "PASS",
                                    "Active provider live probe",
                                    format!(
                                        "LIVE Custom /models reached {} and confirmed model {}",
                                        profile.endpoint, context.active.model
                                    ),
                                ),
                                Ok(Ok(models)) => check(
                                    "WARN",
                                    "Active provider live probe",
                                    format!(
                                        "LIVE Custom /models succeeded but active model {} was absent from {} discovered models",
                                        context.active.model, models.len()
                                    ),
                                ),
                                Ok(Err(error)) => check(
                                    "WARN",
                                    "Active provider live probe",
                                    format!("LIVE Custom probe failed: {}", safe_diagnostic(&error)),
                                ),
                                Err(_) => check(
                                    "WARN",
                                    "Active provider live probe",
                                    "LIVE Custom probe timed out after 12s".into(),
                                ),
                            }
                        }
                        Err(error) => check(
                            "WARN",
                            "Active provider live probe",
                            safe_diagnostic(&error),
                        ),
                    }
                } else {
                    check(
                        "SKIPPED",
                        "Active provider live probe",
                        "managed-provider completion probe skipped to avoid billable/destructive traffic; local auth/model state checked above".into(),
                    );
                }
            }
            Err(error) => check(
                "FAIL",
                "Active provider/auth/model",
                safe_diagnostic(&error),
            ),
        }
        match ProviderProfileStore::new(self.storage.clone()).list(principal) {
            Ok(profiles) if profiles.is_empty() => check(
                "SKIPPED",
                "Custom profile reachability cache",
                "no Custom profiles".into(),
            ),
            Ok(profiles) => {
                let unreachable = profiles
                    .iter()
                    .filter(|profile| profile.reachability == "unreachable")
                    .count();
                let ages = profiles
                    .iter()
                    .map(|profile| diagnostic_cache_age(profile.last_probe_at.as_deref()))
                    .collect::<Vec<_>>()
                    .join(", ");
                check(
                    if unreachable == 0 { "PASS" } else { "WARN" },
                    "Custom profile reachability cache",
                    format!(
                        "CACHED · {} profiles; {unreachable} unreachable; age={}",
                        profiles.len(),
                        if ages.is_empty() {
                            "unknown"
                        } else {
                            ages.as_str()
                        }
                    ),
                );
            }
            Err(error) => check(
                "FAIL",
                "Custom profile reachability cache",
                safe_diagnostic(&error),
            ),
        }
        check(
            if cfg.ipc.ip().is_ok_and(|ip| ip.is_loopback()) {
                "PASS"
            } else {
                "FAIL"
            },
            "Admin API backend",
            format!("bind={}", cfg.ipc.bind),
        );
        check(
            "PASS",
            "Root AI shell: DISABLED",
            "enforced by architecture".into(),
        );
        View {
            title: Some("DOCTOR".into()),
            blocks: vec![Block::List {
                ordered: false,
                items: checks,
            }],
            actions: vec![],
            side_mode: false,
        }
    }

    fn memory_store(&self) -> MemoryStore {
        match &self.runtime {
            Some(runtime) => MemoryStore::with_workspace(self.storage.clone(), runtime.workspace()),
            None => MemoryStore::new(self.storage.clone()),
        }
    }

    fn telegram_skills_view(&self, principal: &str, page: usize) -> Result<View> {
        let store = SkillStore::new(self.storage.clone());
        let learned = store
            .list_all(principal, 500)?
            .into_iter()
            .filter(|skill| skill.source_kind == "learned")
            .collect::<Vec<_>>();
        let pagination = Paginator::new(learned.len(), page, 5);
        let visible = &learned[pagination.range()];
        let rows = visible
            .iter()
            .enumerate()
            .map(|(index, skill)| {
                vec![
                    (index + 1).to_string(),
                    skill.name.clone(),
                    skill.summary.clone(),
                ]
            })
            .collect();
        let mut actions = if visible.is_empty() {
            Vec::new()
        } else {
            vec![visible
                .iter()
                .enumerate()
                .map(|(index, skill)| {
                    Action::command(
                        (index + 1).to_string(),
                        format!("/skills detail {}", skill.id),
                    )
                })
                .collect()]
        };
        actions.push(vec![
            Action::command("‹", format!("/skills learned {}", pagination.previous())),
            Action::noop(format!("Page {}/{}", pagination.page(), pagination.pages())),
            Action::command("›", format!("/skills learned {}", pagination.next())),
        ]);
        actions.push(vec![Action::close()]);
        Ok(View {
            title: Some("LEARNED SKILLS".into()),
            blocks: if visible.is_empty() {
                vec![Block::Paragraph {
                    text: "No successfully learned internal skills are available yet.".into(),
                }]
            } else {
                vec![Block::Table {
                    headers: vec!["No".into(), "Skill".into(), "Description".into()],
                    rows,
                }]
            },
            actions,
            side_mode: false,
        })
    }

    fn telegram_skill_detail_view(&self, principal: &str, skill: &str) -> Result<View> {
        let record = SkillStore::new(self.storage.clone())
            .view(principal, skill)?
            .filter(|record| record.source_kind == "learned")
            .ok_or_else(|| anyhow!("learned skill not found"))?;
        Ok(View {
            title: Some("LEARNED SKILL".into()),
            blocks: vec![
                Block::Table {
                    headers: vec!["Field".into(), "Value".into()],
                    rows: vec![
                        vec!["Name".into(), record.name],
                        vec!["Description".into(), record.summary],
                        vec!["Prerequisites".into(), record.prerequisites],
                        vec!["Updated".into(), record.updated_at],
                    ],
                },
                Block::Paragraph {
                    text: format!(
                        "When to use:\n{}\n\nVerification:\n{}\n\nUsage count is recorded when available in the learning history.",
                        record.when_to_use, record.verification
                    ),
                },
            ],
            actions: vec![vec![Action::back(), Action::close()]],
            side_mode: false,
        })
    }

    fn tools_view(&self) -> View {
        let capabilities = self
            .runtime
            .as_ref()
            .map(|runtime| runtime.capabilities().list())
            .unwrap_or_default();
        let rows = capabilities
            .into_iter()
            .take(40)
            .map(|capability| {
                let marker = match capability.status {
                    CapabilityStatus::Available => "✓",
                    CapabilityStatus::MissingInstallable => "○",
                    CapabilityStatus::ApprovalRequired => "!",
                    _ => "×",
                };
                vec![
                    marker.into(),
                    capability.name,
                    capability.status.as_str().into(),
                ]
            })
            .collect();
        View {
            title: Some("TOOLS & CAPABILITIES".into()),
            blocks: vec![Block::Table {
                headers: vec!["".into(), "Capability".into(), "State".into()],
                rows,
            }],
            actions: vec![vec![Action::command("Refresh", "/tools"), Action::close()]],
            side_mode: false,
        }
    }
}

fn help_view() -> View {
    View {
        title: Some("HELP".into()),
        blocks: vec![Block::Paragraph {
            text: TelegramCommandRegistry::help_text(),
        }],
        actions: vec![vec![Action::close()]],
        side_mode: false,
    }
}

fn diagnostic_cache_age(timestamp: Option<&str>) -> String {
    let Some(timestamp) = timestamp else {
        return "never".into();
    };
    let Ok(parsed) = chrono::DateTime::parse_from_rfc3339(timestamp) else {
        return "unknown".into();
    };
    let age = chrono::Utc::now().signed_duration_since(parsed.with_timezone(&chrono::Utc));
    if age.num_seconds() < 0 {
        return "clock-skew".into();
    }
    if age.num_minutes() < 1 {
        format!("{}s", age.num_seconds())
    } else if age.num_hours() < 1 {
        format!("{}m", age.num_minutes())
    } else if age.num_days() < 1 {
        format!("{}h", age.num_hours())
    } else {
        format!("{}d", age.num_days())
    }
}

fn safe_diagnostic(error: &impl std::fmt::Display) -> String {
    crate::security::redact::redact_text(&error.to_string())
        .chars()
        .take(600)
        .collect()
}
