pub mod agent;
pub mod app;
pub mod attachments;
pub mod auth;
pub mod cli;
pub mod command;
pub mod config;
pub mod context;
pub mod control_plane;
pub mod event;
pub mod identity;
pub mod ipc;
pub mod learning;
pub mod memory;
pub mod owner;
#[allow(dead_code)]
pub mod providers;
pub mod runtime;
pub mod security;
pub mod semantic;
pub mod session;
pub mod skills;
pub mod standalone;
pub mod storage;
pub mod telegram;
pub mod tools;

pub const VERSION: &str = env!("CARGO_PKG_VERSION");
pub mod cli_contract;
pub mod presentation;
